sudo: false
language: node_js
branches:
    only:
      - master
node_js:
    - '4'
    - '6'
    - '8'
before_script: npm install coveralls
script: npm run test
after_script: test $TRAVIS_NODE_VERSION = "8" && nyc report --reporter=text-lcov | coveralls
deploy:
    provider: npm
    email: mitmaro@gmail.com
    api_key:
        secure: "oHu+68ljHtcV7KAd9uRngsAWG0M/83TBsyL1lCLwBYvIr2KD+bay3duUEC7F6BrUWc4nonCdyOmBVIKKE6YZ8zWSudNJ1YpkQSBM9b4ytU3oyjoIpPpZZZS+jZ1pl6s/4P80vjMCImTPAtGEWiOwqM+xXe4jK0eVo/NPQMw8iy+1LtKZ1E6dtraHrcUZnmmBsK5KD5XtV0z/cPputfsGH1mlTsgy+3hYGCFZ1TdO59Y5x4GcbqVnJeAGMx8xHZWD8YtgNLwVxh3lay7cFNr0gI37s52svE7GHLzu487GZLX5+C1HRXykvp5Rtfvm0ioSx4O2PwYHTrEbDa4kDhfK6poq8WWoYD2f2mqrAMs1/1zXiNcuzewatIKriBUfL0a0b/9x3/RxDwgk+1DZIdwmsZbT9ICQo2Ct7OkVuhABiSjVOkO6UJ9Ut0DS/yotevMXi17t+FqPV4wrev0ufhAjo+Ocol+aKc3dHW4YgamaQF7Ma90vG3s4iiSisPHyZGDxHkZLbqNHI6/Pevinks1P9Kyp5k+Fv7yaw12Ig27iDwPWtnU/IGZncRlqYL46Z/yhxu9td/T3mzzS/ydL3V4sEu34jiRN8m3hLoHLKSH4ooDNCRhI22txnWn+DPW5N8geqCNai4OqifjMX0xxtOEuiFVluskxNWWrA4BwU03ecIo="
    on:
        tags: true
        repo: MitMaro/server-shutdown
        node: '8'
