sudo: false
language: node_js
branches:
    only:
        - master
node_js:
    - "4.1.0"
    - "4"
    - "6.0.0"
    - "6"
before_script:
    - npm install coveralls
after_script:
    - test $TRAVIS_NODE_VERSION = "6" && npm run test:coveralls
